"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronDown, FileText, Phone, Plus, Printer, Search, UserRound, WalletCards, X } from "lucide-react";
import { store } from "@/lib/store";
import type { Customer, Order, OrderStatus, Service } from "@/lib/types";

const statuses:OrderStatus[]=["طلب جديد","في انتظار الوثائق","جاهز للمعالجة","قيد الإنجاز","في انتظار الرد","مكتمل"];
const documentNames=["بطاقة التعريف","شهادة الإقامة","شهادة التسجيل","كشف النقاط","صورة شمسية","صك بريدي"];
type Doc={name:string;required:boolean;received:boolean};

export default function NewOrderPage(){
 const router=useRouter();
 const [customers,setCustomers]=useState<Customer[]>([]); const [services,setServices]=useState<Service[]>([]); const [orders,setOrders]=useState<Order[]>([]);
 const [search,setSearch]=useState(""); const [customer,setCustomer]=useState<Customer|null>(null); const [serviceId,setServiceId]=useState(""); const [status,setStatus]=useState<OrderStatus>("طلب جديد");
 const [price,setPrice]=useState(0); const [paid,setPaid]=useState(0); const [notes,setNotes]=useState(""); const [docs,setDocs]=useState<Doc[]>(documentNames.map(name=>({name,required:false,received:false})));
 const [customerModal,setCustomerModal]=useState(false); const [newCustomer,setNewCustomer]=useState({firstName:"",lastName:"",phone:"",wilaya:"",commune:""}); const [receipt,setReceipt]=useState<Order|null>(null);
 useEffect(()=>{setCustomers(store.customers());setServices(store.services().filter(s=>s.enabled));setOrders(store.orders())},[]);
 const selectedService=services.find(s=>s.id===serviceId);
 const filteredCustomers=useMemo(()=>search.trim()?customers.filter(c=>`${c.firstName} ${c.lastName} ${c.phone}`.toLowerCase().includes(search.toLowerCase())).slice(0,6):[],[customers,search]);
 const remaining=Math.max(price-paid,0);
 function chooseService(id:string){setServiceId(id);const s=services.find(x=>x.id===id);if(s)setPrice(s.price)}
 function toggleDoc(index:number,key:"required"|"received"){setDocs(v=>v.map((d,i)=>i===index?{...d,[key]:!d[key],...(key==="received"&&!d.received?{required:true}:{})}:d))}
 function addCustomer(){if(!newCustomer.firstName.trim()||!newCustomer.phone.trim()) return alert("الاسم ورقم الهاتف مطلوبان"); const c:Customer={id:crypto.randomUUID(),...newCustomer,createdAt:new Date().toISOString()};const next=[c,...customers];setCustomers(next);store.saveCustomers(next);setCustomer(c);setCustomerModal(false);setNewCustomer({firstName:"",lastName:"",phone:"",wilaya:"",commune:""});}
 function createOrder(print=false){if(!customer)return alert("اختر الزبون أولًا");if(!selectedService)return alert("اختر الخدمة");if(paid>price)return alert("المبلغ المدفوع لا يمكن أن يتجاوز السعر"); const number=String(orders.length+24).padStart(4,"0"); const o:Order={id:crypto.randomUUID(),orderNumber:`HCT-2026-${number}`,customerId:customer.id,customerName:`${customer.firstName} ${customer.lastName}`.trim(),phone:customer.phone,serviceId:selectedService.id,serviceTitle:selectedService.title,status,price,paid,notes,documents:docs.filter(d=>d.required),createdAt:new Date().toISOString()}; const next=[o,...orders];setOrders(next);store.saveOrders(next);setReceipt(o);if(print)setTimeout(()=>window.print(),250)}
 return <div className="mx-auto max-w-7xl animate-enter">
  <header className="mb-6"><p className="text-sm font-black text-blue-600">معاملة جديدة</p><h1 className="mt-1 text-3xl font-black text-slate-950">إضافة طلب جديد</h1><p className="mt-2 text-sm font-medium text-slate-400">من الزبون إلى الإيصال في شاشة واحدة.</p></header>
  <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-5">
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><UserRound size={20}/></div><div><h2 className="font-black text-slate-900">الزبون</h2><p className="text-xs font-semibold text-slate-400">ابحث بالاسم أو الهاتف أو أضف زبونًا جديدًا</p></div></div>{customer?<div className="flex items-center justify-between rounded-xl border border-blue-100 bg-blue-50/70 p-4"><div><p className="font-black text-slate-900">{customer.firstName} {customer.lastName}</p><p className="mt-1 flex items-center gap-1 text-xs font-bold text-slate-500"><Phone size={13}/>{customer.phone}</p></div><button onClick={()=>setCustomer(null)} className="rounded-lg bg-white px-3 py-2 text-xs font-black text-blue-600">تغيير</button></div>:<><div className="relative"><Search size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="محمد أو 0550..." className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pr-11 pl-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/>{filteredCustomers.length>0&&<div className="absolute right-0 left-0 top-14 z-20 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{filteredCustomers.map(c=><button key={c.id} onClick={()=>{setCustomer(c);setSearch("")}} className="flex w-full items-center justify-between border-b border-slate-100 p-4 text-right last:border-0 hover:bg-slate-50"><div><p className="font-black text-slate-800">{c.firstName} {c.lastName}</p><p className="mt-1 text-xs text-slate-400">{c.phone}</p></div><Plus size={17} className="text-blue-600"/></button>)}</div>}</div><button onClick={()=>setCustomerModal(true)} className="mt-4 flex items-center gap-2 text-sm font-black text-blue-600"><Plus size={17}/> إضافة زبون جديد</button></>}</section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-900">الخدمة والحالة</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="mb-2 block text-xs font-black text-slate-600">الخدمة</span><div className="relative"><select value={serviceId} onChange={e=>chooseService(e.target.value)} className="h-12 w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"><option value="">اختر الخدمة</option>{services.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/></div></label><label><span className="mb-2 block text-xs font-black text-slate-600">حالة الطلب</span><select value={status} onChange={e=>setStatus(e.target.value as OrderStatus)} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50">{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-amber-600"><FileText size={20}/></div><div><h2 className="font-black text-slate-900">الوثائق</h2><p className="text-xs font-semibold text-slate-400">حدد المطلوب وما تم استلامه</p></div></div><div className="overflow-hidden rounded-xl border border-slate-200">{docs.map((d,i)=><div key={d.name} className="grid grid-cols-[1fr_auto_auto] items-center gap-2 border-b border-slate-100 p-3 last:border-0"><p className="text-sm font-black text-slate-700">{d.name}</p><button onClick={()=>toggleDoc(i,"required")} className={`rounded-lg px-2.5 py-2 text-[11px] font-black ${d.required?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-400"}`}>مطلوبة</button><button onClick={()=>toggleDoc(i,"received")} className={`rounded-lg px-2.5 py-2 text-[11px] font-black ${d.received?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-400"}`}>{d.received?"✓ مستلمة":"مستلمة"}</button></div>)}</div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label><span className="mb-2 block font-black text-slate-900">ملاحظات</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="أي معلومة خاصة بهذا الطلب..." className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label></section>
  </div><aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><WalletCards size={20}/></div><div><h2 className="font-black text-slate-900">الدفع</h2><p className="text-xs font-semibold text-slate-400">حساب الباقي آليًا</p></div></div><div className="space-y-4"><label><span className="mb-2 block text-xs font-black text-slate-600">سعر الخدمة</span><input type="number" min={0} value={price} onChange={e=>setPrice(Number(e.target.value))} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-left font-black outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label><label><span className="mb-2 block text-xs font-black text-slate-600">المبلغ المدفوع</span><input type="number" min={0} value={paid} onChange={e=>setPaid(Number(e.target.value))} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-left font-black outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label></div><div className="mt-5 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex justify-between text-xs font-bold text-slate-400"><span>المتبقي</span><span>دج</span></div><p className="mt-2 text-3xl font-black">{remaining.toLocaleString()}</p></div></section><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black text-slate-400">ملخص الطلب</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-3"><span className="text-slate-400">الزبون</span><strong className="text-left text-slate-800">{customer?`${customer.firstName} ${customer.lastName}`:"—"}</strong></div><div className="flex justify-between gap-3"><span className="text-slate-400">الخدمة</span><strong className="text-left text-slate-800">{selectedService?.title||"—"}</strong></div><div className="flex justify-between"><span className="text-slate-400">الحالة</span><strong>{status}</strong></div></div></section><button onClick={()=>createOrder(false)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-4 font-black text-white shadow-lg shadow-blue-200"><Check size={18}/> إنشاء الطلب</button><button onClick={()=>createOrder(true)} className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-4 font-black text-slate-700"><Printer size={18}/> إنشاء وطباعة الإيصال</button></aside></div>
  {customerModal&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[26px] bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-black">زبون جديد</h2><p className="mt-1 text-xs font-bold text-slate-400">سيتم اختياره تلقائيًا بعد الحفظ.</p></div><button onClick={()=>setCustomerModal(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><X size={17}/></button></div><div className="grid gap-3 sm:grid-cols-2">{[["firstName","الاسم *"],["lastName","اللقب"],["phone","الهاتف *"],["wilaya","الولاية"],["commune","البلدية"]].map(([k,l])=><label key={k}><span className="mb-2 block text-xs font-black text-slate-600">{l}</span><input value={newCustomer[k as keyof typeof newCustomer]} onChange={e=>setNewCustomer({...newCustomer,[k]:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setCustomerModal(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-500">إلغاء</button><button onClick={addCustomer} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">حفظ واختيار</button></div></div></div>}
  {receipt&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm"><div className="w-full max-w-sm"><div className="print-receipt rounded-[24px] bg-white p-6 shadow-2xl"><div className="border-b border-dashed border-slate-300 pb-5 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 font-black text-white">H+</div><h2 className="mt-3 text-xl font-black">HOCINE TECH+</h2><p className="mt-1 text-xs font-bold text-slate-400">وصل استلام طلب</p></div><div className="space-y-3 py-5 text-sm">{[["رقم الطلب",receipt.orderNumber],["الزبون",receipt.customerName],["الهاتف",receipt.phone],["الخدمة",receipt.serviceTitle],["الحالة",receipt.status],["السعر",`${receipt.price.toLocaleString()} دج`],["المدفوع",`${receipt.paid.toLocaleString()} دج`],["المتبقي",`${(receipt.price-receipt.paid).toLocaleString()} دج`]].map(([l,v])=><div key={l} className="flex justify-between gap-3"><span className="font-bold text-slate-400">{l}</span><strong className="text-left">{v}</strong></div>)}</div><div className="border-t border-dashed border-slate-300 pt-4 text-center text-xs font-bold text-slate-500">شكرًا لثقتكم في HOCINE TECH+</div></div><div className="no-print mt-3 grid grid-cols-2 gap-2"><button onClick={()=>window.print()} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">طباعة</button><button onClick={()=>{setReceipt(null);router.push("/dashboard/orders")}} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-700">إنهاء</button></div></div></div>}
 </div>
}
