"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Search, UserPlus, X, Phone, MapPin } from "lucide-react";
import { store } from "@/lib/store";
import type { Customer } from "@/lib/types";

export default function CustomersPage(){
 const [customers,setCustomers]=useState<Customer[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({firstName:"",lastName:"",phone:"",wilaya:"",commune:"",notes:""});
 useEffect(()=>setCustomers(store.customers()),[]);
 const filtered=useMemo(()=>customers.filter(c=>`${c.firstName} ${c.lastName} ${c.phone} ${c.wilaya||""} ${c.commune||""}`.toLowerCase().includes(q.toLowerCase())),[customers,q]);
 function save(){ if(!form.firstName.trim()||!form.phone.trim()) return alert("الاسم ورقم الهاتف مطلوبان"); const c:Customer={id:crypto.randomUUID(),...form,createdAt:new Date().toISOString()}; const next=[c,...customers]; setCustomers(next); store.saveCustomers(next); setForm({firstName:"",lastName:"",phone:"",wilaya:"",commune:"",notes:""}); setOpen(false); }
 return <div className="mx-auto max-w-7xl animate-enter">
  <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-blue-600">إدارة العملاء</p><h1 className="mt-1 text-3xl font-black text-slate-950">الزبائن</h1><p className="mt-2 text-sm font-medium text-slate-400">قاعدة موحدة لكل زبائن المحل وبيانات الاتصال بهم.</p></div><button onClick={()=>setOpen(true)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-100"><UserPlus size={18}/> إضافة زبون</button></header>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="relative"><Search size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو رقم الهاتف أو الولاية..." className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pr-11 pl-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></div></div>
   <div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><article key={c.id} className="card-hover rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 font-black text-blue-700">{c.firstName.charAt(0)}</div><div className="min-w-0"><h3 className="truncate font-black text-slate-900">{c.firstName} {c.lastName}</h3><p className="mt-1 flex items-center gap-1 text-xs font-semibold text-slate-400"><Phone size={13}/>{c.phone}</p>{(c.wilaya||c.commune)&&<p className="mt-1 flex items-center gap-1 text-xs font-semibold text-slate-400"><MapPin size={13}/>{[c.commune,c.wilaya].filter(Boolean).join("، ")}</p>}</div></div>{c.notes&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs font-medium leading-6 text-slate-500">{c.notes}</p>}</article>)}{filtered.length===0&&<div className="col-span-full p-12 text-center text-sm font-bold text-slate-400">لا يوجد زبائن مطابقون للبحث.</div>}</div>
  </section>
  {open&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-[26px] bg-white p-5 shadow-2xl md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black text-slate-950">إضافة زبون جديد</h2><p className="mt-1 text-xs font-semibold text-slate-400">يكفي الاسم ورقم الهاتف، والباقي اختياري.</p></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-500"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2">
    {[["firstName","الاسم *"],["lastName","اللقب"],["phone","رقم الهاتف *"],["wilaya","الولاية"],["commune","البلدية"]].map(([key,label])=><label key={key} className="block"><span className="mb-2 block text-xs font-black text-slate-600">{label}</span><input value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label>)}
    <label className="sm:col-span-2"><span className="mb-2 block text-xs font-black text-slate-600">ملاحظات</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label>
   </div><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-black text-slate-600">إلغاء</button><button onClick={save} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white"><Plus size={17}/> حفظ الزبون</button></div></div></div>}
 </div>
}
