"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import StatusBadge from "@/components/status-badge";
import { store } from "@/lib/store";
import type { Order, OrderStatus } from "@/lib/types";
const statuses:OrderStatus[]=["طلب جديد","في انتظار الوثائق","جاهز للمعالجة","قيد الإنجاز","في انتظار الرد","مكتمل","ملغى"];
export default function OrdersPage(){
 const [orders,setOrders]=useState<Order[]>([]); const [q,setQ]=useState(""); const [filter,setFilter]=useState<"الكل"|OrderStatus>("الكل");
 useEffect(()=>setOrders(store.orders()),[]);
 const filtered=useMemo(()=>orders.filter(o=>(filter==="الكل"||o.status===filter)&&`${o.orderNumber} ${o.customerName} ${o.phone} ${o.serviceTitle}`.toLowerCase().includes(q.toLowerCase())),[orders,q,filter]);
 function updateStatus(id:string,status:OrderStatus){const next=orders.map(o=>o.id===id?{...o,status}:o);setOrders(next);store.saveOrders(next)}
 return <div className="mx-auto max-w-7xl animate-enter"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-blue-600">متابعة العمل</p><h1 className="mt-1 text-3xl font-black text-slate-950">الطلبات</h1><p className="mt-2 text-sm font-medium text-slate-400">تابع كل تسجيل وغيّر حالته مباشرة من القائمة.</p></div><Link href="/dashboard/orders/new" className="flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white"><Plus size={18}/> طلب جديد</Link></header>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="space-y-4 border-b border-slate-100 p-5"><div className="relative"><Search size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث برقم الطلب، اسم الزبون، الهاتف أو الخدمة..." className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pr-11 pl-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></div><div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setFilter("الكل")} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${filter==="الكل"?"bg-slate-950 text-white":"bg-slate-100 text-slate-500"}`}>الكل</button>{statuses.map(s=><button key={s} onClick={()=>setFilter(s)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${filter===s?"bg-blue-600 text-white":"bg-slate-100 text-slate-500"}`}>{s}</button>)}</div></div>
   <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-right"><thead className="bg-slate-50 text-[11px] font-black text-slate-400"><tr><th className="p-4">رقم الطلب</th><th className="p-4">الزبون</th><th className="p-4">الخدمة</th><th className="p-4">الدفع</th><th className="p-4">الحالة</th><th className="p-4">تغيير الحالة</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(o=><tr key={o.id} className="hover:bg-slate-50"><td className="p-4 text-xs font-black text-blue-700">{o.orderNumber}</td><td className="p-4"><p className="text-sm font-black text-slate-800">{o.customerName}</p><p className="mt-1 text-[11px] text-slate-400">{o.phone}</p></td><td className="p-4 text-sm font-bold text-slate-600">{o.serviceTitle}</td><td className="p-4"><p className="text-xs font-black text-slate-800">{o.paid.toLocaleString()} / {o.price.toLocaleString()} دج</p><p className="mt-1 text-[10px] text-slate-400">متبقي {(o.price-o.paid).toLocaleString()} دج</p></td><td className="p-4"><StatusBadge status={o.status}/></td><td className="p-4"><select value={o.status} onChange={e=>updateStatus(o.id,e.target.value as OrderStatus)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600 outline-none">{statuses.map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>
   <div className="divide-y divide-slate-100 md:hidden">{filtered.map(o=><article key={o.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-blue-700">{o.orderNumber}</p><h3 className="mt-1 font-black text-slate-900">{o.customerName}</h3><p className="mt-1 text-xs font-semibold text-slate-400">{o.serviceTitle}</p></div><StatusBadge status={o.status}/></div><div className="mt-4 flex items-center justify-between"><p className="text-xs font-bold text-slate-500">{o.paid.toLocaleString()} / {o.price.toLocaleString()} دج</p><select value={o.status} onChange={e=>updateStatus(o.id,e.target.value as OrderStatus)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600">{statuses.map(s=><option key={s}>{s}</option>)}</select></div></article>)}</div>
   {filtered.length===0&&<div className="p-12 text-center text-sm font-bold text-slate-400">لا توجد طلبات مطابقة.</div>}
  </section>
 </div>
}
