"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Search, ToggleLeft, ToggleRight, X } from "lucide-react";
import { store } from "@/lib/store";
import type { Service } from "@/lib/types";

export default function ServicesPage(){
 const [services,setServices]=useState<Service[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({title:"",category:"",price:0});
 useEffect(()=>setServices(store.services()),[]);
 const filtered=useMemo(()=>services.filter(s=>`${s.title} ${s.category}`.toLowerCase().includes(q.toLowerCase())),[services,q]);
 function persist(next:Service[]){setServices(next);store.saveServices(next)}
 function add(){if(!form.title.trim()||!form.category.trim())return alert("اسم الخدمة والتصنيف مطلوبان");persist([{id:crypto.randomUUID(),...form,enabled:true},...services]);setForm({title:"",category:"",price:0});setOpen(false)}
 function toggle(id:string){persist(services.map(s=>s.id===id?{...s,enabled:!s.enabled}:s))}
 return <div className="mx-auto max-w-7xl animate-enter"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-blue-600">إدارة الكتالوج</p><h1 className="mt-1 text-3xl font-black text-slate-950">الخدمات</h1><p className="mt-2 text-sm font-medium text-slate-400">أضف الخدمات وحدد أسعارها الافتراضية وإتاحتها.</p></div><button onClick={()=>setOpen(true)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white"><Plus size={18}/> إضافة خدمة</button></header>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="relative"><Search size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم الخدمة أو التصنيف..." className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pr-11 pl-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(s=><article key={s.id} className={`card-hover rounded-2xl border p-4 ${s.enabled?"border-slate-200 bg-white":"border-slate-200 bg-slate-50 opacity-65"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-black text-blue-600">{s.category}</p><h3 className="mt-1 font-black text-slate-900">{s.title}</h3><p className="mt-3 text-sm font-black text-slate-700">{s.price.toLocaleString()} دج</p></div><button onClick={()=>toggle(s.id)} className={s.enabled?"text-emerald-600":"text-slate-400"}>{s.enabled?<ToggleRight size={34}/>:<ToggleLeft size={34}/>}</button></div><p className={`mt-4 text-xs font-black ${s.enabled?"text-emerald-600":"text-slate-400"}`}>{s.enabled?"الخدمة ظاهرة ومتاحة":"الخدمة مخفية"}</p></article>)}</div></section>
  {open&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[26px] bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">خدمة جديدة</h2><p className="mt-1 text-xs font-bold text-slate-400">يمكن تعديل السعر داخل الطلب لاحقًا.</p></div><button onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><X size={17}/></button></div><div className="space-y-4"><label className="block"><span className="mb-2 block text-xs font-black text-slate-600">اسم الخدمة</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label><label className="block"><span className="mb-2 block text-xs font-black text-slate-600">التصنيف</span><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="مثال: التربية والتعليم" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label><label className="block"><span className="mb-2 block text-xs font-black text-slate-600">السعر الافتراضي</span><input type="number" min={0} value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-500">إلغاء</button><button onClick={add} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">حفظ الخدمة</button></div></div></div>}
 </div>
}
